language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    # - LUA=lua5.3
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - sudo apt-get install p7zip-full
  - sudo apt-get install zlib1g-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/
  - bash .travis/setup_lua.sh
  - sudo luarocks install Lua-cURL         --server=https://rocks.moonscript.org/dev
  - sudo luarocks install luacov-coveralls --server=https://rocks.moonscript.org/dev
  - sudo luarocks install lunitx           --server=https://rocks.moonscript.org/manifests/moteus
  - sudo luarocks install luacrypto
  - sudo luarocks install lua-iconv
  - sudo luarocks install lbase64
  - if [ $LUA = "lua5.1" ]; then
      sudo luarocks install bit32;
    fi

install:
  - sudo luarocks make rockspecs/zipwriter-scm-0.rockspec

script: 
  - cd test
  - lunit.sh test.lua

after_success:
  - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
